Updated

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,6 +12,8 @@ jobs:
        run: echo "this workflow run successfully for this particular action"
 
      - name: Simulating error
-       run: echo "error taking place": exit 1
+       run: |
+        echo "error taking place"
+        exit 1
      
      
