simulating error

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,4 +10,8 @@ jobs:
 
      - name: Run a sample github action
        run: echo "this workflow run successfully for this particular action"
+
+     - name: simulating error
+       run: echo "error taking place": exit 1
+     
      
